@ProductWebApi_HostAddress = https://localhost:7105

GET {{ProductWebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{ProductWebApi_HostAddress}}/api/products
Content-Type: application/json

{
  "Id": 2,
  "Name": "Tent",
  "Description": "A tent to sleep in",
  "Price": 149.99,
  "CategoryId": 1,
  "StockQuantity": 25,
  "CreatedDate": "2024-06-01T10:00:00Z",
  "IsActive": true
}

###

GET {{ProductWebApi_HostAddress}}/api/products

###
